# .streamlit/secrets.toml
FIREBASE_RTDB_URL = "https://site-acd03-default-rtdb.firebaseio.com/"

# Se suas regras do Firebase Realtime Database exigirem autenticação (RECOMENDADO):
# FIREBASE_AUTH_TOKEN = "SEU_TOKEN_DE_AUTENTICACAO_OU_SEGREDO_DO_BANCO_DE_DADOS"
# Nota: Usar um segredo do banco de dados legado é menos seguro.
# Para produção, investigue o uso de ID Tokens do Firebase Auth.